# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Google Search MCP
FROM node:lts-alpine AS builder

# Install build tools
RUN apk add --no-cache python3 make g++

WORKDIR /app

# Copy dependency and TS config
COPY package.json yarn.lock tsconfig.json ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy source files
COPY src ./src

# Build TypeScript project
RUN yarn build

# Install Playwright browsers
RUN npx playwright install chromium

# Production image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy artifacts
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json .

ENV NODE_ENV=production

# Default command
CMD ["node", "dist/index.js"]
